spring.application.name=account-service
server.port=8081

resilience4j.circuitbreaker.instances.loanService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.loanService.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.loanService.sliding-window-size=2
resilience4j.circuitbreaker.instances.loanService.wait-duration-in-open-state=10s