spring.application.name=account-service

server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1
# Circuit Breaker
resilience4j.circuitbreaker.instances.loanService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.loanService.minimum-number-of-calls=10
resilience4j.circuitbreaker.instances.loanService.sliding-window-size=10
resilience4j.circuitbreaker.instances.loanService.wait-duration-in-open-state=10s

# Retry
resilience4j.retry.instances.loanServiceRetry.max-attempts=3
resilience4j.retry.instances.loanServiceRetry.wait-duration=2s